<?php
return [
    // 登录页不检测安全
    'App\Modules\ModuleShop\Http\Controllers\Admin\LoginController' => 'nocheck',
    // 后台所有控制器都控制登录
    'App\Modules\ModuleShop\Http\Controllers\Admin' => 'site.login',
    'App\Http\Controllers\SiteAdmin' => 'site.login',
    // 首页概况
    'App\Modules\ModuleShop\Http\Controllers\Admin\IndexController@index' => 'site.login',
    // 会员列表
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getList' => 'member.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getInfo' => 'member.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@delete' => 'member.detail.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@add' => 'member.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@edit' => 'member.detail.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@status' => 'member.detail.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@export' => 'member.export.operate',
    // 粉丝列表
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\FansController@getList' => 'fans.view',
    // 会员详情
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getMemberInfoBaseConfig' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getMemberInfo' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getDistributorInfo' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getDistributorSubList' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getAgentInfo' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberController@getAgentSubList' => 'member.detail.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@setAgentLevel' => 'member.detail.operate',
    // 会员标签
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLabelController@edit' => 'member.label.operate',
    //'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLabelController@getList' => 'member.label.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLabelController@delete' => 'member.label.operate',
    // 订单设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\OrderConfigController@getInfo' => 'order.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\OrderConfigController@add' => 'order.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\OrderConfigController@edit' => 'order.config.operate',
    // 短信设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\SmsConfigController@getInfo' => 'sms.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\SmsConfigController@add' => 'sms.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\SmsConfigController@edit' => 'sms.config.operate',
    // 商户设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\StoreConfigController@add' => 'store.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\StoreConfigController@edit' => 'store.config.operate',
    // 后台提现设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\WithdrawConfigController@getInfo' => 'withdraw.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\WithdrawConfigController@add' => 'withdraw.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\WithdrawConfigController@edit' => 'withdraw.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\WithdrawConfigController@checkPayConfig' => 'withdraw.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\WithdrawConfigController@updateWithdrawConfig' => 'withdraw.config.operate',
    // 支付设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\PayConfigController@getInfo' => 'pay.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\PayConfigController@add' => 'pay.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\PayConfigController@edit' => 'pay.config.operate',
    // 商城设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\ShopConfigController@getInfo' => 'shop.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\ShopConfigController@add' => 'shop.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\ShopConfigController@edit' => 'shop.config.operate',
    // 会员等级
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLevelController@getInfo' => 'member.level.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLevelController@add' => 'member.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLevelController@edit' => 'member.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLevelController@status' => 'member.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberLevelController@transfer' => 'member.level.operate',
    // 运费模板路由(因为供应商商品有运费模板的添加)
    // 'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@getList' => 'logistics.view',
    // 'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@getInfo' => 'logistics.view',
     'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@add' => 'logistics.operate',
     'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@edit' => 'logistics.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@delete' => 'logistics.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\FreightTemplateController@getDistrictJs' => 'site.login',
    // 商品列表
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getList' => 'product.view,dealer.level.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@uploadProductImage' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@uploadProductSkuImage' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@saveProductData' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getProductData' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@addProduct' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getProductQrCode' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@exportProductList' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@editProductStatus' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getFenxiaoProductData' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@saveFenxiaoProductData' => 'product.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getMaxCommission' => 'product.view',
    // 获取分销选择的商城商品详情
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getFenxiaoShopProductData' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductController@getProductCount' => 'product.view',
    // 商品分类
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@saveClass' => 'product.class.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@deleteClass' => 'product.class.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@getProductsCount' => 'product.class.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@getClassList' => 'product.class.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@editProductClassName' => 'product.class.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@uploadClassImage' => 'product.class.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductClassController@editProductClassStatus' => 'product.class.operate',
    // 会员配置
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberConfigController@getInfo' => 'member.level.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Member\MemberConfigController@save' => 'member.level.operate',
    // 积分管理
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointController@getList' => 'point.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointController@getMemberList' => 'point.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointController@add' => 'point.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointController@export' => 'point.view',
    // 积分配置
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointConfigController@getInfo' => 'point.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Point\PointConfigController@save' => 'point.operate',
    // 分销设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionSettingController@getInfo' => 'distributor.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionSettingController@edit' => 'distributor.config.operate',
    // 分销等级
    #'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@getList' => 'distributor.level.view,dealer.level.view,agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@getInfo' => 'distributor.level.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@add' => 'distributor.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@edit' => 'distributor.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@disable' => 'distributor.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@enable' => 'distributor.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributionLevelController@trans' => 'distributor.level.operate',
    // 分销商管理
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@getList' => 'distributor.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@getInfo' => 'distributor.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@review' => 'distributor.review.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@delete' => 'distributor.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@disposeSubDistributor' => 'distributor.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@deleteInReview' => 'distributor.review.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@add' => 'distributor.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@edit' => 'distributor.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Distribution\DistributorController@reviewDistributorInfo' => 'distributor.view',
    // 优惠券
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@add' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@edit' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@delete' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@editStatus' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@getInfo' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@getProductClass' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@getList' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@getCouponItem' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@getMemberAndLevel' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@sendCoupon' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@checkCouponAmount' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponController@export' => 'coupon.view',
    // 优惠券明细
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@getList' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@confirm' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@export' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@getList' => 'coupon.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@confirm' => 'coupon.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Coupon\CouponItemController@export' => 'coupon.view',
    // 订单
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@getList' => 'order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@getInfo' => 'order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@deliver' => 'order.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@export' => 'order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@edit' => 'order.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\AfterSaleController@getList' => 'order.after-sale.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\AfterSaleController@getInfo' => 'order.after-sale.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\AfterSaleController@editStatus' => 'order.after-sale.operate,finance.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\AfterSaleController@export' => 'order.after-sale.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\LogisticsController@getInfo' => 'order.view,cloudstock.order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\LogisticsController@edit' => 'order.operate',
    // 同步订单到快递接口
    'App\Modules\ModuleShop\Http\Controllers\Admin\Order\OrderController@syncOrder' => 'order.operate',
    // 页面模块编辑
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@save' => 'page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@publish' => 'page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Url\UrlManageController@getStaticUrl' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Url\UrlManageController@getProductClassUrl' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Url\UrlManageController@getProductDetailUrl' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Url\UrlManageController@getPageUrl' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@getPageList' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@setHomePage' => 'page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@deletePage' => 'page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@getHomePage' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@getHomePageQrCode' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@addPage' => 'page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@addBlankPage' => 'page.operate',
    // 广告屏页面模块编辑
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@bigScreenGetHomePage' => 'bigscreen.page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@bigScreenSave' => 'bigscreen.page.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\MobilePageController@bigScreenAddBlankPage' => 'bigscreen.page.operate',
    // 模板配色
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Template\TemplateMobiController@getList' => 'page.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\StyleColor\StyleColorController@getSiteColor' => 'color.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\StyleColor\StyleColorController@editSiteColor' => 'color.operate',
    // 店铺底部菜单编辑
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\NavMobileController@getInfo' => 'nav.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\NavMobileController@save' => 'nav.operate',
    // 广告屏底部菜单编辑
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\NavMobileController@bigScreenGetInfo' => 'bigscreen.nav.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\UI\Design\NavMobileController@bigScreenSave' => 'bigscreen.nav.operate',
    // 财务
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\BalanceController@getList' => 'commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\BalanceController@export' => 'commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\WithdrawController@getList' => 'withdraw.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\WithdrawController@getInfo' => 'withdraw.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\WithdrawController@export' => 'withdraw.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\WithdrawController@withDraw' => 'withdraw.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\WithdrawController@reject' => 'withdraw.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\FinanceController@getList' => 'finance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\FinanceController@export' => 'finance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\FinanceController@rechange' => 'balance.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\RechargeController@getlist' => 'balance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\RechargeController@getInfo' => 'balance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\RechargeController@verify' => 'balance.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\RechargeController@getBalanceList' => 'balance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Finance\RechargeController@export' => 'balance.operate',

    // 员工相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteRoleController@getList' => 'role.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteRoleController@getInfo' => 'role.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteRoleController@save' => 'role.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteRoleController@delete' => 'role.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminController@getList' => 'staff.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminController@getInfo' => 'staff.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminController@save' => 'staff.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminController@status' => 'staff.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminController@password' => 'site.login',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminDepartmentController@save' => 'department.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminDepartmentController@delete' => 'department.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminDepartmentController@saveSort' => 'department.operate',
    //'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminDepartmentController@getList' => 'department.view',
    //'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminDepartmentController@getSubInfo' => 'department.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminAllocationController@save' => 'staff.allocate.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Site\SiteAdminAllocationController@getInfo' => 'staff.allocate.view',

    // 公众号配置
    //'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxConfigController@getInfo' => 'mp.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxConfigController@save' => 'mp.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxConfigController@unBind' => 'mp.config.operate',
    // 公众号菜单
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxMenuController@getList' => 'mp.menu.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxMenuController@save' => 'mp.menu.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxMenuController@delete' => 'mp.menu.operate',
    // 公众号自动回复
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxAutoReplyController@getList' => 'mp.reply.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxAutoReplyController@getInfo' => 'mp.reply.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxAutoReplyController@save' => 'mp.reply.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxAutoReplyController@delete' => 'mp.reply.operate',
    // 公众号素材
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxNewsController@getList' => 'mp.media.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxNewsController@getItemList' => 'mp.media.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxNewsController@getInfo' => 'mp.media.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxNewsController@save' => 'mp.media.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Wx\WxNewsController@delete' => 'mp.media.operate',
    // 消息推送
    'App\Modules\ModuleShop\Http\Controllers\Admin\Message\MessageConfigController@getInfo' => 'notice.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Message\MessageConfigController@save' => 'notice.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Message\MessageConfigController@getList' => 'notice.config.view',
    // 海报相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\SharePaper\PaperMobiController@getInfo' => 'poster.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SharePaper\PaperMobiController@save' => 'poster.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SharePaper\PaperMobiController@getConfig' => ' poster.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SharePaper\PaperMobiController@savePaperShow' => 'poster.config.operate',
    // 文字替换
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\CustomWordController@getInfo' => 'word.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\CustomWordController@save' => 'word.operate',
    // 商品参数
    // 'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductParamTemplateController@getList' => 'product.param.view',
    // 'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductParamTemplateController@getInfo' => 'product.param.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductParamTemplateController@save' => 'product.param.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductParamTemplateController@delete' => 'product.param.operate',
    // 通用配置（版本设置需要用到这个接口，所以要注释）
    // 'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\ConfigController@getInfo' => 'site.config.view',
    //'App\Modules\ModuleShop\Http\Controllers\Admin\SiteConfig\ConfigController@save' => 'site.config.operate',
    // 商品评论
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductCommentController@getList' => 'product.comment.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductCommentController@add' => 'product.comment.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductCommentController@adminReply' => 'product.comment.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductCommentController@delete' => 'product.comment.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Product\ProductCommentController@status' => 'product.comment.operate',
    // 通用方法
    'App\Modules\ModuleShop\Http\Controllers\Admin\Common\CommonController@getProductList' => 'site.login',
    // 代理配置
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentUpgradeSettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentUpgradeSettingController@edit' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentBaseSettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentBaseSettingController@edit' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentSaleRewardSettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentSaleRewardSettingController@edit' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardSettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardSettingController@save' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardSettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardSettingController@save' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardRuleController@getList' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardRuleController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardRuleController@save' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardRuleController@delete' => 'agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentApplySettingController@getInfo' => 'agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentApplySettingController@edit' => 'agent.config.operate',
    // 代理分红
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentOrderCommisionController@getList' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentOrderCommisionController@export' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentSaleRewardController@getList' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentSaleRewardController@export' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardController@getList' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardController@getInfo' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardController@check' => 'agent.commission.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentRecommendRewardController@export' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardController@getList' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardController@getInfo' => 'agent.commission.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardController@check' => 'agent.commission.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentPerformanceRewardController@export' => 'agent.commission.view',
    // 代理业绩
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@getPerformanceList' => 'agent.performance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@exportPerformanceList' => 'agent.performance.view',
    // 代理代理
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@getAgentList' => 'agent.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@adminAddAgent' => 'agent.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@cancelAgent' => 'agent.operate',
    // 代理代理审核
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@verifyAgent' => 'agent.review.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@getApplyAgentList' => 'agent.review.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Agent\AgentController@delAgentRejectApplyData' => 'agent.review.operate',
    // 经销商相关 - 授权证书
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@getList' => 'dealer.authcert.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@getInfo' => 'dealer.authcert.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@getApplySettingInfo' => 'dealer.authcert.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@delete' => 'dealer.authcert.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@save' => 'dealer.authcert.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\AuthCertController@saveApplySettingInfo' => 'dealer.authcert.operate',
    // 经销商相关 - 授权邀请
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\DealerInvite\InvitePosterController@getInfo' => 'dealer.dealerinvite.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Dealer\DealerInvite\InvitePosterController@save' => 'dealer.dealerinvite.operate',
    // 经销商相关 - 其它
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerApplySettingController@getInfo' => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerApplySettingController@edit' => 'dealer.config.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@getPermList" => 'dealer.level.view',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@getInfo" => 'dealer.level.view',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@add" => 'dealer.level.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@edit" => 'dealer.level.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@disable" => 'dealer.level.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@enable" => 'dealer.level.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@delete" => 'dealer.level.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerLevelController@getEnabledWeight" => 'dealer.level.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceController@getPerformanceList' => 'dealer.performance.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceController@exportPerformanceList' => 'dealer.performance.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRewardController@getInfo' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRewardController@verify' => 'cloudstock.settle.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRewardController@exchange' => 'cloudstock.settle.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceRewardController@getList' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceRewardController@export' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRecommendRewardController@getList' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRecommendRewardController@export' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerSaleRewardController@getList' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerSaleRewardController@export' => 'cloudstock.settle.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerBaseSettingController@getInfo' => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerBaseSettingController@edit' => 'dealer.config.operate',
    //'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@getDealerList' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@adminAddDealer' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@cancelDealer' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@resumeAgent' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@verifyDealer' => 'dealer.review.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@getApplyDealerList' => 'dealer.review.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerController@delDealerRejectApplyData' => 'dealer.review.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerWithdrawConfigController@getInfo" => 'dealer.config.view',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerWithdrawConfigController@edit" => 'dealer.config.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerWithdrawConfigController@updateWithdrawConfig' => 'dealer.config.operate',
    "App\Modules\ModuleShop\Http\Admin\Dealer\DealerWithdrawConfigController@checkPayConfig" => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceRewardSettingController@getInfo' => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerPerformanceRewardSettingController@save' => 'dealer.config.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRecommendRewardSettingController@getInfo' => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerRecommendRewardSettingController@save' => 'dealer.config.operate',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerSaleRewardSettingController@getInfo' => 'dealer.config.view',
    'App\Modules\ModuleShop\Http\Admin\Dealer\DealerSaleRewardSettingController@save' => 'dealer.config.operate',
    // 云仓相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@getList' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@getSkuList' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@getSkuLogList' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@getSettleSummary' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@getSettleList' => 'dealer.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@setStatus' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@addProduct' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@add' => 'dealer.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockController@adjustInventory' => 'dealer.operate',
    // 云仓进货单相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\PurchaseOrderController@getList' => 'cloudstock.order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\PurchaseOrderController@getOrderInfo' => 'cloudstock.order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\PurchaseOrderController@financeReview' => 'finance.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\PurchaseOrderController@editRemarkInside' => 'cloudstock.order.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\PurchaseOrderController@orderManualStockDeliver' => 'cloudstock.order.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\TakeDeliveryOrderController@getList' => 'cloudstock.order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\TakeDeliveryOrderController@getOrderInfo' => 'cloudstock.order.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\TakeDeliveryOrderController@orderDeliver' => 'cloudstock.order.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\TakeDeliveryOrderController@editRemarkInside' => 'cloudstock.order.operate',
    //云仓结算相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\CloudStock\CloudStockSkuSettleController@getList' => 'cloudstock.settle.view',
    // 充值赠送优惠
    'App\Modules\ModuleShop\Http\Controllers\Admin\Promotions\RechargeBonusController@getInfo' => 'rechargebonus.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Promotions\RechargeBonusController@save' => 'rechargebonus.operate',
    // 防伪码相关
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeController@getCodeList' => 'security.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeController@deleteCode' => 'security.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeController@exportCodeList' => 'security.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeBatchController@add' => 'security.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeBatchController@getBatchList' => 'security.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\ProductSecurity\SecurityCodeBatchController@deleteBatch' => 'security.operate',

    //直播
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@getList' => 'live.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@getInfo' => 'live.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@delete' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@close' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@open' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@setMuted' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@setOnScreenCoupon' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@setOnScreenProduct' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@add' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@edit' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@uploadLiveImage' => 'live.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Live\LiveController@uploadNavCustomImage' => 'live.operate',

    // 拼团
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@getSettingList' => 'group.buying.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@getList' => 'group.buying.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@getInfo' => 'group.buying.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@getProductSku' => 'group.buying.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingProductController@getList' => 'group.buying.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@save' => 'group.buying.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@setEnd' => 'group.buying.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\GroupBuying\GroupBuyingController@delete' => 'group.buying.operate',


    // 区域代理业绩
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentPerformanceController@export' => 'area.agent.performance.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentPerformanceController@getList' => 'area.agent.performance.view',
    // 区域代理审核
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentApplySettingController@getInfo' => 'area.agent.apply.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentApplySettingController@edit' => 'area,agent.apply.operate',
    // 区域代理等级
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentLevelController@AreaEdit' => 'area.agent.level.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentLevelController@index' => 'area.agent.level.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentLevelController@getInfo' => 'area.agent.level.view',
    // 区域代理设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentBaseSettingController@getInfo' => 'area.agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentBaseSettingController@edit' => 'area.agent.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentApplySettingController@getInfo' => 'area.agent.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\AreaAgent\AreaAgentApplySettingController@edit' => 'area.agent.config.view',

    // 供应商结算
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierSettleController@getList' => 'supplier.settle.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierSettleController@export' => 'supplier.settle.view',
    // 供应商设置
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierBaseSettingController@getInfo' => 'supplier.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierBaseSettingController@edit' => 'supplier.config.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierWithdrawConfigController@getInfo' => 'supplier.config.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierWithdrawConfigController@edit' => 'supplier.config.operate',
    // 供应商列表
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierController@add' => 'supplier.list.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierController@cancel' => 'supplier.list.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierController@recover' => 'supplier.list.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierController@getList' => 'supplier.list.view',
    // 供应商产品审核
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierProductController@getWaitVerifyProductList' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierProductController@getWaitVerifyProductInfo' => 'product.view',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Supplier\SupplierProductController@verifyProducts' => 'product.operate',
    // 快递发货
    'App\Modules\ModuleShop\Http\Controllers\Admin\Express\ExpressSettingController@edit' => 'express.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Express\ExpressSettingController@refreshToken' => 'express.operate',
    'App\Modules\ModuleShop\Http\Controllers\Admin\Express\ExpressSettingController@getInfo' => 'express.view',
];
